### ISSUE TITLE
DDS control

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Pounder#10]
What shall I do with P3...P0, SYNC_IN, IO_Update pins? Shall I route them to ordinary IOs or there are some special wishes?
And what about using QSPI in STM32. It is optimized for FLASH, but one can disable addressing and transfer ordinary data as well.

**Comment by gkasprow** [comment]
@jordens did you use STM32 QSPI FLASH interface in SDIO mode? AD9959 has such access mode.

**Comment by jordens** [comment]
I haven't used the quadspi peripheral. Might work with that dds.

**Comment by gkasprow** [comment]
Let's add 0R resistor option so we can switch to SPI in case of issues.

**Comment by jordens** [comment]
The quadspi Periphareral is ok for this. Memory mapped access will be of very limited use because of the variable register length. For phase locking (fiber length stabilization is a pll) doing it on both channels would be tricky because of the way the target channel is switched. But that's a limitation of the dds, not the spi bus.

**Comment by jordens** [comment]
* SYNC_IN should be a CPU timer channel output and SYNC_OUT should also go to a timer input. Or ignore both if you are short on pins.
* IO_UPDATE and P0-3 should go to GPIOs, preferrable within the same GPIO bank of the CPU.

**Comment by gkasprow** [comment]
control signals assignment
![obraz](https://user-images.githubusercontent.com/4325054/69904708-18395500-13aa-11ea-8225-0d03395cd11a.png)
![obraz](https://user-images.githubusercontent.com/4325054/69904711-1f606300-13aa-11ea-825d-cf9ec0a33cc6.png)
